# Practical session week 2 - Rectangular data and Pandas — Solution

## Purpose
Give an introduction to  
* Jupyter Notebook
* Rectangular data
* Variables and records
* Independent and dependent variables
* Pandas and Numpy Libraries
* Exploratory Data Analysis

## Methodology
We will use the Pandas library to load a dataset, perform operations, and conduct some data analysis. Some challenges are presented at the end.

## Results
Practical knowledge of how to load, write, and manipulate rectangular data in Python. This is our first hands-on session with real data.

## Suggested next steps
The next step is to explore data visualizations such as bar charts for category counts, histograms for numeric distributions, and scatter plots for relationships between two numeric variables. This will be the topic of next week.

# Jupyter Notebooks

For this notebook, use a Python environment with Jupyter, NumPy, and Pandas installed. Anaconda is one possible environment manager, but any environment containing these packages will work.

JupyterLab or Jupyter Notebook will be our preferred working environment.

Jupyter Notebooks are composed of cells.

Cells can contain Markdown or code.  

- **Markdown cells** contain explanations, headings, lists, links, images, and formulas. Useful syntax includes `# Heading`, `**bold**`, `*italic*`, `` `code` ``, and `- list item`.

- **Code cells** contain Python instructions that can be executed. The result appears directly below the cell.

The shortcuts below are enough for the activities in this notebook:

Useful Jupyter Notebook shortcuts:
- `Enter`: edit the selected cell.
- `Esc`: leave edit mode and enter command mode.
- `A`: create a cell above the current cell while in command mode.
- `B`: create a cell below the current cell while in command mode.
- `Shift + Enter`: execute the cell and move to the next one.
- `Ctrl + Enter`: execute the cell and remain on it.
- `D`, `D`: delete the selected cell while in command mode.
- `Z`: undo a deleted cell while in command mode.

## Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. Also, it offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.

In [ ]:
import numpy as np

For one-dimensional arrays, `np.dot(a, b)` multiplies corresponding values and adds the products, producing the dot product. Use `help(np.dot)` in the next cell to display the function's explanation and parameters without leaving the notebook.

## Before moving forward

Explore Numpy `dot` function

In [ ]:
v1 = [1, 2, 3, 4]
v2 = [3, 2, 5, 4]

np.dot(v1, v2)

np.int64(38)

In [ ]:
help(np.dot)

Help on _ArrayFunctionDispatcher in module numpy:

dot(...)
    dot(a, b, out=None)

    Dot product of two arrays. Specifically,

    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).

    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.

    - If either `a` or `b` is 0-D (scalar), it is equivalent to
      :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
      preferred.

    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.

    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of
      `b`::

        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

    It uses an optimized BLAS library when possible (see `numpy.linalg`).

    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : ndarray, optional
        Output argument. This must have the exact kind that would be returned
        if it was not used. In particular, it must have the right type, must be
        C-contiguous, and its dtype must be the dtype that would be returned
        for `dot(a,b)`. This is a performance feature. Therefore, if these
        conditions are not met, an exception is raised, instead of attempting
        to be flexible.

    Returns
    -------
    output : ndarray
        Returns the dot product of `a` and `b`.  If `a` and `b` are both
        scalars or both 1-D arrays then a scalar is returned; otherwise
        an array is returned.
        If `out` is given, then it is returned.

    Raises
    ------
    ValueError
        If the last dimension of `a` is not the same size as
        the second-to-last dimension of `b`.

    See Also
    --------
    vdot : Complex-conjugating dot product.
    tensordot : Sum products over arbitrary axes.
    einsum : Einstein summation convention.
    matmul : '@' operator as method with out parameter.
    linalg.multi_dot : Chained dot product.

    Examples
    --------
    >>> import numpy as np
    >>> np.dot(3, 4)
    12

    Neither argument is complex-conjugated:

    >>> np.dot([2j, 3j], [2j, 3j])
    (-13+0j)

    For 2-D arrays it is the matrix product:

    >>> a = [[1, 0], [0, 1]]
    >>> b = [[4, 1], [2, 2]]
    >>> np.dot(a, b)
    array([[4, 1],
           [2, 2]])

    >>> a = np.arange(3*4*5*6).reshape((3,4,5,6))
    >>> b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
    >>> np.dot(a, b)[2,3,2,1,2,2]
    499128
    >>> sum(a[2,3,2,:] * b[1,2,:,2])
    499128

Explore Numpy functions `linalg.norm` to obtain the magnitude/norm of the vectors `v1` and `v2`

In [ ]:
np.linalg.norm(v1), np.linalg.norm(v2)

(np.float64(5.477225575051661), np.float64(7.3484692283495345))

Consider the cosine similarity function we build from scrach last week:

$$
  cos(v1, v2) = \frac{v1 . v2}{\lVert v1 \rVert \times \lVert v2 \rVert}
$$

Explore Numpy functions `linalg.norm` e `dot` and **re-write the cosine function** below without using a `for` loop.

In [ ]:
def cosine_similarity(v1, v2):
    return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))

cosine_similarity(v1, v2)

np.float64(0.9441175904999112)

## Rectangular data

Many datasets used in Data Science are tabular, like a spreadsheet or database table. A rectangular dataset has rows and columns. If it has `n` rows and `m` columns, its dimensions are `n × m`.

* A **column** in the table is commonly referred to as a **variable**.
    * A variable may also be called an attribute, input, predictor, or feature.
* A **row** in the table is commonly referred to as a **record**.
    * A record may also be called a case, example, instance, observation, pattern, or sample.


A rectangular dataset can therefore be understood as a two-dimensional structure: rows identify observations and columns describe characteristics of those observations.

What are independent and dependent variables?  

<details>
<p>
    
- An **independent variable** is used to explain or predict another variable. In an experiment, it may be changed or controlled to observe its effect.  
    
- A **dependent variable** is the result being measured, explained, or predicted.
    
</p>
</details>

In Data Science, we often investigate how independent variables relate to or help predict a dependent variable.

What other names are given to these variables?

<details>
<p>

An **independent variable** may also be called a predictor, explanatory variable, feature, input, covariate, or risk factor.
    
A **dependent variable** may also be called a response, outcome, target, label, or output.


    
</p>
</details>

## Pandas

In [ ]:
import pandas as pd

What is Pandas?

Pandas is a Python library for organizing, cleaning, transforming, and analyzing tabular data. Its two main data structures are:

- **Series**: a one-dimensional sequence of values with labels. A single DataFrame column is a Series.
- **DataFrame**: a two-dimensional table with labeled rows and columns. Different columns may contain different data types.

In this notebook, Pandas will be used to create DataFrames, read and write CSV files, inspect datasets, select rows and columns, and filter records using logical conditions. You can inspect any Pandas object or function inside Jupyter with `help(...)` or by placing `?` after its name, for example `pd.DataFrame?`.

### Lets use Pandas to create a retangular dataset

The DataFrame object is a 2-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table. It is generally the most commonly used pandas object.

#### Constructing DataFrame

A Pandas DataFrame can be constructed in a variety of ways.

One of them is from a list of dicts:

Let's create a DataFrame from a list of dictionaries. Each dictionary represents a record and the keys represent the variables.

Desired DataFrame:

```python
     a	b
0	0	0
1	1	2
2	2	4
```

In [ ]:
# Each dictionary is one row of the DataFrame.
data = [
    {"a": 0, "b": 0},
    {"a": 1, "b": 2},
    {"a": 2, "b": 4},
]

df = pd.DataFrame(data)
df

   a  b
0  0  0
1  1  2
2  2  4

Pandas creates tabular data structures called DataFrames and missing values are represented as `NaN` (**Not a Number**)
- if you don't provide values for a column, pandas will fill it with `NaN`
- Handling missing values is a big part of data cleaning and preparation process and defining strategies to deal with them are really important.

In [ ]:
df = pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

In [ ]:
df

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

A DataFrame object has has an `index` and a `column` attribute
- `index` indicates the start, end (exclusive) and increment of the row indices

In [ ]:
df.index

RangeIndex(start=0, stop=2, step=1)

- `columns` indicates the **column names** of the DataFrame and can be used to access columns

In [ ]:
df.columns

Index(['a', 'b', 'c'], dtype='object')

**Casting to other data types** may help when working with those columns, try casting `df.columns` to a list

In [ ]:
list(df.columns)

['a', 'b', 'c']

We can **rename** columns using the `rename` method

- Note that the columns were defined by the dictionary keys
- `inplace=True` will modify the DataFrame **in place**, otherwise a new DataFrame will be returned and the original will remain unchanged

In [ ]:
# before:
df = pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])
df

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [ ]:
# after
df.rename(columns={"a": "data", "b": "science"}, inplace=True)
df

   data  science    c
0   1.0        2  NaN
1   NaN        3  4.0

#### Creating your own DataFrame

Before learning more details and operations on DataFrames, lets create our own.

In [ ]:
name_list = ["ana", "bruno", "carlos"]
shoe_list = [38, 39, 42]
height_list = [168, 170, 174]
gender_list = ["female", "male", "male"]

students_df = pd.DataFrame({
    "name": name_list,
    "shoe": shoe_list,
    "height": height_list,
})
students_df

     name  shoe  height
0     ana    38     168
1   bruno    39     170
2  carlos    42     174

Print the `columns` of the DataFrame

In [ ]:
students_df.columns

Index(['name', 'shoe', 'height'], dtype='object')

Print the `index` of the DataFrame

In [ ]:
students_df.index

RangeIndex(start=0, stop=3, step=1)

We forgot the **gender data**. This is how we can add a new column to the DataFrame after it has been created

In [ ]:
students_df["gender"] = gender_list
students_df

     name  shoe  height  gender
0     ana    38     168  female
1   bruno    39     170    male
2  carlos    42     174    male

We may have also introduced a wrong value. We can **access** it or **change** it using `loc`

In [ ]:
students_df.loc[2]

name      carlos
shoe          42
height       174
gender      male
Name: 2, dtype: object

We can also use the `iloc` method to access data by **position**
- use `iloc` to access the last row of the DataFrame

In [ ]:
students_df.iloc[-1]

name      carlos
shoe          42
height       174
gender      male
Name: 2, dtype: object

- Use `iloc` to access the last element of the last column of the DataFrame
    
    - **Tip**: the DataFrame is matrix-like, so you can use the same indexing as you would use in a matrix (even negative indices work)

In [ ]:
students_df.iloc[-1, -1]

'male'

## Write and Read a csv file

We can use Pandas to perform both operations.
Run the cell below and check on your folder if the file was created.

In [ ]:
students_df.to_csv('students.csv', index=False)

Read a csv file into a DataFrame - by **default**, `read_csv` assumes that the **delimiter is a comma**

In [ ]:
students_df2 = pd.read_csv('students.csv')

Let's check if `students_df` is equal to `students_df2` using `.equals` method

In [ ]:
students_df.equals(students_df2)

True

When saving a DataFrame to a csv file, we can specify the `index` (`True` | `False`)

## Operations on pandas DataFrames

In this section you will learn about some DataFrame methods like `head` and `tail`.

### Subset of rows (records)

#### Select the first n rows

In [ ]:
students_df.head(2)

    name  shoe  height  gender
0    ana    38     168  female
1  bruno    39     170    male

#### Select the last rows

In [ ]:
students_df.tail(2)

     name  shoe  height gender
1   bruno    39     170   male
2  carlos    42     174   male

#### Get a random sample of n rows

In [ ]:
students_df.sample(2, random_state=42)

    name  shoe  height  gender
0    ana    38     168  female
1  bruno    39     170    male

#### Select rows by position
- select the **first and second rows**

In [ ]:
students_df.iloc[:2]

    name  shoe  height  gender
0    ana    38     168  female
1  bruno    39     170    male

#### Select rows that meet logical criteria
- select all students with `height` of **170cm or higher**

In [ ]:
students_df.loc[students_df["height"] >= 170]

     name  shoe  height gender
1   bruno    39     170   male
2  carlos    42     174   male

#### Select rows based on multiple conditions
- select all `male` students with `height` of **172cm or higher**

In [ ]:
students_df.loc[(students_df["gender"] == "male") & (students_df["height"] >= 172)]

     name  shoe  height gender
2  carlos    42     174   male

- select all `female` students with `height` of **172cm or higher**

In [ ]:
students_df.loc[(students_df["gender"] == "female") & (students_df["height"] >= 172)]

Empty DataFrame
Columns: [name, shoe, height, gender]
Index: []

### Subset of columns (variables)

#### Select columns by name

In [ ]:
students_df["name"]

0       ana
1     bruno
2    carlos
Name: name, dtype: object

Select subset of columns `name` and `gender`

In [ ]:
students_df[["name", "gender"]]

     name  gender
0     ana  female
1   bruno    male
2  carlos    male

#### Select columns by position
Using `iloc[rows, columns]` to select
- select the **first and third columns** of the dataframe

In [ ]:
students_df.iloc[:, [0, 2]]

     name  height
0     ana     168
1   bruno     170
2  carlos     174

### Subset of both rows and columns
- select the rows where the `shoe` size is **greater than 40** and **only** the columns `name` and `shoe`

In [ ]:
students_df.loc[students_df["shoe"] > 40, ["name", "shoe"]]

     name  shoe
2  carlos    42

### Summing Up

* When selecting subsets of data, square brackets `[]` are used.
* Inside these brackets, you can use a single column/row label, a list of column/row labels, a slice of labels, a conditional expression or a column.
* Select specific rows and/or columns using **loc** when using the row and column names.
* Select specific rows and/or columns using **iloc** when using the positions in the table.
* You can assign new values to a selection based on **loc/iloc**.

#### Quick reference

```python
df["column"]                              # one column
df[["column_a", "column_b"]]            # multiple columns
df[df["column"] >= value]                 # rows matching one condition
df[(condition_a) & (condition_b)]          # both conditions must be true
df[(condition_a) | (condition_b)]          # at least one condition must be true
df.loc[row_condition, ["column_a", "column_b"]]  # rows and named columns
df.iloc[row_positions, column_positions]   # rows and columns by position
```

Use parentheses around every condition combined with `&` or `|`.

## Challenges

In these challenges you will handle a bigger dataset.

There are a few first questions you need to know how to answer before reading a CSV file with Pandas

- Does the CSV have a header line?
- Is there an index column?
- What is the separator character on the CSV file?
- If there are missing values, is there any specific word being used to describe a missing value?

Then, these details can be handled by specifing some parameters as `sep`, `na_values` or `index_col`.

### Challenge 1 - Load the dataset

In [ ]:
df_titanic = pd.read_csv('titanic.csv')

### Challenge 2 - Validate the loading

1. Show the first 10 rows and confirm if the table matches with the lines

In [ ]:
df_titanic.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

2. Try the DataFrame method `info`. It is a nice alternative. What information do you get from this?

In [ ]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

### Challenge 3 - Some basic EDA

**EDA** stands for `Exploratory Data Analysis`. It is used by data scientists to analyze and investigate data sets and summarize their main characteristics, often employing data visualization methods.

Try executing `df_titanic.describe()`.

In [ ]:
df_titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

After investigating the results, describe them and comment on the usefulness of this Pandas function.

In [ ]:
# describe() summarizes each numeric variable with its count, mean,
# standard deviation, minimum, quartiles, and maximum. It provides a quick
# view of typical values, variation, ranges, and possible unusual values.

Now, try `.info()` method.

In [ ]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

What information do you get from this?

In [ ]:
# info() shows the number of rows and columns, each column name and data
# type, the number of non-null values, and approximate memory usage.
# Comparing the non-null count with 891 reveals columns with missing values.

### Challenge 4 - Getting to know your data

What do the results above tell you about each variable? Do you actually know what they mean? Understanding the meaning and encoding of every variable is a crucial step before drawing conclusions from a dataset.

#### Titanic data dictionary

| Variable | Meaning |
|---|---|
| `PassengerId` | Unique identifier assigned to each passenger. |
| `Survived` | Survival outcome: `0` means no and `1` means yes. This can be treated as the dependent or target variable. |
| `Pclass` | Ticket class: `1` = first, `2` = second, and `3` = third class. It can also serve as an approximate indicator of socioeconomic status. |
| `Name` | Passenger's recorded name, often including a title such as Mr., Mrs., or Miss. |
| `Sex` | Passenger's recorded sex: `male` or `female`. |
| `Age` | Age in years. Ages below one year may appear as decimal values. Some ages are missing. |
| `SibSp` | Number of siblings and spouses travelling with the passenger. |
| `Parch` | Number of parents and children travelling with the passenger. |
| `Ticket` | Ticket identifier. Passengers travelling together may share a ticket. |
| `Fare` | Passenger fare. |
| `Cabin` | Cabin number. Most records do not contain a cabin value. |
| `Embarked` | Port of embarkation: `C` = Cherbourg, `Q` = Queenstown, and `S` = Southampton. |

This file contains 891 passenger records. Missing values occur in `Age` (177 records), `Cabin` (687 records), and `Embarked` (2 records). A missing value is not zero; it means that the information was not recorded.

Using the outputs from `info()` and `describe()`, identify which variables are numeric, which are categorical, which contain missing values, and which variables might help explain `Survived`. Write your observations below.

In [ ]:
# Survived and Pclass are stored as integers but represent categories.
# Age and Fare are numeric measurements. Sex and Embarked are categorical.
# Age, Cabin, and Embarked contain missing values. Survived is the target;
# variables such as Pclass, Sex, Age, SibSp, Parch, Fare, and Embarked may
# help explain differences in the survival outcome.

---

## Reinforcement exercises - Filtering and selecting data

These exercises revisit the Pandas operations used above. Work through them in order: the filters become gradually more detailed, but every question can be solved with the ideas already introduced in this notebook.

Remember to put each condition inside parentheses when combining conditions with `&` (and) or `|` (or).

### R-01 - First-class passengers

Filter `df_titanic` to show only passengers from first class (`Pclass` equal to `1`).

In [ ]:
df_titanic[df_titanic["Pclass"] == 1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

### R-02 - Women who survived

Filter the rows for passengers whose `Sex` is `female` **and** whose `Survived` value is `1`.

In [ ]:
df_titanic[(df_titanic["Sex"] == "female") & (df_titanic["Survived"] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

### R-03 - Young adults and selected columns

Select passengers aged from 18 to 29, including 18 but excluding 30. Show only the columns `Name`, `Age`, and `Pclass`.

Use `loc` to apply the row filter and select the columns in the same expression.

In [ ]:
df_titanic.loc[(df_titanic["Age"] >= 18) & (df_titanic["Age"] < 30), ["Name", "Age", "Pclass"]]

                                                  Name   Age  Pclass
0                              Braund, Mr. Owen Harris  22.0       3
2                               Heikkinen, Miss. Laina  26.0       3
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0       3
12                      Saundercock, Mr. William Henry  20.0       3
23                        Sloper, Mr. William Thompson  28.0       1
..                                                 ...   ...     ...
883                      Banfield, Mr. Frederick James  28.0       2
884                             Sutehall, Mr. Henry Jr  25.0       3
886                              Montvila, Rev. Juozas  27.0       2
887                       Graham, Miss. Margaret Edith  19.0       1
889                              Behr, Mr. Karl Howell  26.0       1

[271 rows x 3 columns]

### R-04 - Children or older passengers

Select passengers younger than 12 **or** aged 60 and above. Show only `Name`, `Age`, `Sex`, and `Pclass`.

In [ ]:
df_titanic.loc[(df_titanic["Age"] < 12) | (df_titanic["Age"] >= 60), ["Name", "Age", "Sex", "Pclass"]]

                                        Name    Age     Sex  Pclass
7             Palsson, Master. Gosta Leonard   2.00    male       3
10           Sandstrom, Miss. Marguerite Rut   4.00  female       3
16                      Rice, Master. Eugene   2.00    male       3
24             Palsson, Miss. Torborg Danira   8.00  female       3
33                     Wheadon, Mr. Edward H  66.00    male       2
..                                       ...    ...     ...     ...
831          Richards, Master. George Sibley   0.83    male       2
850  Andersson, Master. Sigvard Harald Elias   4.00    male       3
851                      Svensson, Mr. Johan  74.00    male       3
852                  Boulos, Miss. Nourelain   9.00  female       3
869          Johnson, Master. Harold Theodor   4.00    male       3

[94 rows x 4 columns]

### R-05 - A more specific passenger profile

Find passengers who travelled in third class, paid a fare greater than 30, **and** survived. Show `Name`, `Pclass`, `Fare`, and `Survived`.

In [ ]:
df_titanic.loc[(df_titanic["Pclass"] == 3) & (df_titanic["Fare"] > 30) & (df_titanic["Survived"] == 1), ["Name", "Pclass", "Fare", "Survived"]]

,Name,Pclass,Fare,Survived
25,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",3,31.3875,1
74,"Bing, Mr. Lee",3,56.4958,1
233,"Asplund, Miss. Lillian Gertrud",3,31.3875,1
261,"Asplund, Master. Edvin Rojj Felix",3,31.3875,1
509,"Lang, Mr. Fang",3,56.4958,1
643,"Foo, Mr. Choong",3,56.4958,1
692,"Lam, Mr. Ali",3,56.4958,1
838,"Chip, Mr. Chang",3,56.4958,1

### R-06 - Women embarking outside Southampton

Select female passengers who embarked at Cherbourg (`C`) **or** Queenstown (`Q`). Show `Name`, `Sex`, `Embarked`, and `Fare`.

Build the two-port condition first, then combine it with the condition for `Sex`.

In [ ]:
df_titanic.loc[((df_titanic["Embarked"] == "C") | (df_titanic["Embarked"] == "Q")) & (df_titanic["Sex"] == "female"), ["Name", "Sex", "Embarked", "Fare"]]

,Name,Sex,Embarked,Fare
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,C,71.2833
9,"Nasser, Mrs. Nicholas (Adele Achem)",female,C,30.0708
19,"Masselmani, Mrs. Fatima",female,C,7.2250
22,"McGowan, Miss. Anna ""Annie""",female,Q,8.0292
28,"O'Dwyer, Miss. Ellen ""Nellie""",female,Q,7.8792
...,...,...,...,...
866,"Duran y More, Miss. Asuncion",female,C,13.8583
874,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,C,24.0000
875,"Najib, Miss. Adele Kiamie ""Jane""",female,C,7.2250
879,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,C,83.1583
885,"Rice, Mrs. William (Margaret Norton)",female,Q,29.1250

### R-07 - Review of selection by position

Using only `iloc`, select the first five rows and the columns in positions 3, 5, and 9 (`Name`, `Age`, and `Fare`).

In [ ]:
df_titanic.iloc[:5, [3, 5, 9]]

                                                Name   Age     Fare
0                            Braund, Mr. Owen Harris  22.0   7.2500
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
2                             Heikkinen, Miss. Laina  26.0   7.9250
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                           Allen, Mr. William Henry  35.0   8.0500

### R-08 - Compare two filtered groups

Create two filtered DataFrames:

1. Adult women (`Age` greater than or equal to 18) who survived.
2. Adult women who did not survive.

Use `len` to print the number of rows in each group. Which group is larger?

In [ ]:
adult_women_survived = df_titanic[(df_titanic["Age"] >= 18) & (df_titanic["Sex"] == "female") & (df_titanic["Survived"] == 1)]
adult_women_not_survived = df_titanic[(df_titanic["Age"] >= 18) & (df_titanic["Sex"] == "female") & (df_titanic["Survived"] == 0)]

print("Adult women who survived:", len(adult_women_survived))
print("Adult women who did not survive:", len(adult_women_not_survived))

# The group of adult women who survived is larger.

Adult women who survived: 159
Adult women who did not survive: 47

### R-09 - Difficult: priority profile

Create one filter for passengers who satisfy **all** of the following:

- they were younger than 16 **or** aged 60 and above;
- they travelled in third class;
- they did not survive.

Show only `Name`, `Age`, `Sex`, `Pclass`, and `Survived`. Store the combined condition in a variable before using `loc`.

In [ ]:
priority_filter = (
    ((df_titanic["Age"] < 16) | (df_titanic["Age"] >= 60))
    & (df_titanic["Pclass"] == 3)
    & (df_titanic["Survived"] == 0)
)

df_titanic.loc[priority_filter, ["Name", "Age", "Sex", "Pclass", "Survived"]]

                                        Name   Age     Sex  Pclass  Survived
7             Palsson, Master. Gosta Leonard   2.0    male       3         0
14      Vestrom, Miss. Hulda Amanda Adolfina  14.0  female       3         0
16                      Rice, Master. Eugene   2.0    male       3         0
24             Palsson, Miss. Torborg Danira   8.0  female       3         0
50                Panula, Master. Juha Niilo   7.0    male       3         0
59        Goodwin, Master. William Frederick  11.0    male       3         0
63                     Skoog, Master. Harald   4.0    male       3         0
111                     Zabour, Miss. Hileni  14.5  female       3         0
116                     Connors, Mr. Patrick  70.5    male       3         0
119        Andersson, Miss. Ellis Anna Maria   2.0  female       3         0
147         Ford, Miss. Robina Maggie "Ruby"   9.0  female       3         0
164             Panula, Master. Eino Viljami   1.0    male       3         0
171                     Rice, Master. Arthur   4.0    male       3         0
182    Asplund, Master. Clarence Gustaf Hugo   9.0    male       3         0
205               Strom, Miss. Telma Matilda   2.0  female       3         0
278                       Rice, Master. Eric   7.0    male       3         0
280                         Duane, Mr. Frank  65.0    male       3         0
326                Nysveen, Mr. Johan Hansen  61.0    male       3         0
352                       Elias, Mr. Tannous  15.0    male       3         0
374               Palsson, Miss. Stina Viola   3.0  female       3         0
386          Goodwin, Master. Sidney Leonard   1.0    male       3         0
419                Van Impe, Miss. Catharina  10.0  female       3         0
480           Goodwin, Master. Harold Victor   9.0    male       3         0
541     Andersson, Miss. Ingeborg Constanzia   9.0  female       3         0
542        Andersson, Miss. Sigrid Elisabeth  11.0  female       3         0
634                       Skoog, Miss. Mabel   9.0  female       3         0
642            Skoog, Miss. Margit Elizabeth   2.0  female       3         0
683              Goodwin, Mr. Charles Edward  14.0    male       3         0
686                 Panula, Mr. Jaako Arnold  14.0    male       3         0
731                 Hassan, Mr. Houssein G N  11.0    male       3         0
787                Rice, Master. George Hugh   8.0    male       3         0
813       Andersson, Miss. Ebba Iris Alfrida   6.0  female       3         0
819             Skoog, Master. Karl Thorsten  10.0    male       3         0
824             Panula, Master. Urho Abraham   2.0    male       3         0
850  Andersson, Master. Sigvard Harald Elias   4.0    male       3         0
851                      Svensson, Mr. Johan  74.0    male       3         0
852                  Boulos, Miss. Nourelain   9.0  female       3         0

---

## Additional Challenge

These challenges will help you get familiar with the most important object of the NumPy library, the array.

### Part I

1. Use the numpy's function `arange` and create the array `my_array` with the sequence of numbers from 0 to 24.

In [ ]:
my_array = np.arange(24)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

2. Use the method `reshape` to redimension the array so that it has 6 rows and 4 columns. What happened? What is the relasionship between the number of elements and the dimensions of a 2D matrix?

In [ ]:
my_array = my_array.reshape((6, 4))
my_array

# A 6 x 4 matrix requires 24 elements: 6 * 4 = 24.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

###  Part II

$$\begin{bmatrix}
1 & 2 & 1 & 7 \\
3 & 0 & 1 & 8 \\
0 & 2 & 4 & 9 \\
2 & 2 & 5 & 5
\end{bmatrix}$$

1. Create this matrix in NumPy

In [ ]:
m = np.array([
    [1, 2, 1, 7],
    [3, 0, 1, 8],
    [0, 2, 4, 9],
    [2, 2, 5, 5],
])
m

array([[1, 2, 1, 7],
       [3, 0, 1, 8],
       [0, 2, 4, 9],
       [2, 2, 5, 5]])

2. Slice the first column

In [ ]:
m[:, 0]

array([1, 3, 0, 2])

3. Slice the first column, but only the second and third rows

In [ ]:
m[1:3, 0]

array([3, 0])

4. Slice the 4 elements at the center of the matrix

In [ ]:
m[1:3, 1:3]

array([[0, 1],
       [2, 4]])

5. Slice the sub-matrix of the 4 elements of the lower right corner, without using the matrix size

In [ ]:
m[-2:, -2:]

array([[4, 9],
       [5, 5]])

6. Slice the sub-matrix of the 4 elements of the upper right corner, without using the matrix size

In [ ]:
m[:2, -2:]

array([[1, 7],
       [1, 8]])

**Expected output**:

```python

first column:
 [1 3 0 2]

first column, rows 2 and 3:
 [3 0]

centre:
 [[0 1]
 [2 4]]

bottom right:
 [[4 9]
 [5 5]]

bottom right:
 [[4 9]
 [5 5]]

top right:
 [[1 7]
 [1 8]]

top right:
 [[1 7]
 [1 8]]

top right:
 [[1 7]
 [1 8]]
```